# =============================================
# CONTROLE DE GASTOS - CONFIGURAÇÕES
# =============================================

# Servidor
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/controlegastos
spring.datasource.username=postgres
spring.datasource.password=2208
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=Y29udHJvbGUtZ2FzdG9zLWFwcC1jaGF2ZS1zZWNyZXRhLXN1cGVyLXNlZ3VyYS0yMDI2LTA1LTI4
jwt.expiration=86400000

# Logs
logging.level.com.allyson=INFO
logging.level.org.springframework.security=WARN